Unify PR workflows

diff --git a/.github/workflows/google_main.yml b/.github/workflows/google_main.yml
--- a/.github/workflows/google_main.yml
+++ b/.github/workflows/google_main.yml
@@ -1,32 +1,77 @@
-name: Update modules/k8s/loki
+name: Update modules/google
 
 on:
   push:
     branches:
       - main
     paths:
-      - 'modules/k8s/loki/**'
+      - 'modules/google/**'
   workflow_dispatch:
 
 jobs:
   build:
-    name: Test modules/k8s/loki
+    name: Test modules/google
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+    - uses: actions/checkout@v4
+      with:
+        fetch-depth: 0
+
+    - name: Get changed files
+      id: changed-files
+      uses: tj-actions/changed-files@v42
+    
     - name: Run tests
       env:
         GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
         GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
         GOOGLE_ZONE:  ${{ secrets.GOOGLE_ZONE }}
         GOOGLE_CREDENTIALS:  ${{ secrets.GOOGLE_CREDENTIALS }}
-        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
-        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
-        AWS_REGION:  ${{ secrets.AWS_REGION }}
+        PR_BRANCH: "main"
         ENTIGO_INFRALIB_DESTROY: false
       run: |
-        modules/k8s/loki/test.sh
+        source common/generate_config.sh
+        prepare_agent
+        echo "sources:
+            - url: https://github.com/entigolabs/entigo-infralib
+              version: main
+              force_version: true
+        steps:" > agents/config.yaml
+
+        default_google_conf
+
+        docker pull $ENTIGO_INFRALIB_IMAGE
+        docker pull $TFLINT_IMAGE
+        run_agents
+        
+        PIDS=""
+        echo "Changed modules:"
+        for module in $(for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
+            echo "$file" | grep "modules/google" | cut -d'/' -f1-3
+        done | sort -u )
+        do
+          ${module}/test.sh testonly &
+          PIDS="$PIDS $!=${module}"
+        done
+
+        FAIL=""
+        for p in $PIDS; do
+            pid=$(echo $p | cut -d"=" -f1)
+            name=$(echo $p | cut -d"=" -f2)
+            wait $pid || FAIL="$FAIL $p"
+            if [[ $FAIL == *$p* ]]
+            then
+              echo "$p Failed"
+            else
+              echo "$p Done"
+            fi
+        done
+        if [ "$FAIL" != "" ]
+        then
+          echo "FAILED TESTS $FAIL"
+          exit 2
+        fi
+
     - name: Get latest release
       id: get_latest_release
       uses: actions/github-script@v6
@@ -50,10 +95,10 @@ jobs:
       run: |
         git config user.name "GitHub Actions"
         git config user.email "actions@github.com"
-        git tag -a modules/k8s/loki-${{ steps.get_latest_release.outputs.new_version }}-rc${{ github.run_number }} -m "Release modules/k8s/loki-${{ steps.get_latest_release.outputs.new_version }}-rc${{ github.run_number }}"
-        git push origin modules/k8s/loki-${{ steps.get_latest_release.outputs.new_version }}-rc${{ github.run_number }}
-        RELEASE_URL=$(gh release create modules/k8s/loki-${{ steps.get_latest_release.outputs.new_version }}-rc${{ github.run_number }} \
-        --title "Release modules/k8s/loki-${{ steps.get_latest_release.outputs.new_version }}-rc${{ github.run_number }}" \
+        git tag -a modules/google-${{ steps.get_latest_release.outputs.new_version }}-rc${{ github.run_number }} -m "Release modules/google-${{ steps.get_latest_release.outputs.new_version }}-rc${{ github.run_number }}"
+        git push origin modules/google-${{ steps.get_latest_release.outputs.new_version }}-rc${{ github.run_number }}
+        RELEASE_URL=$(gh release create modules/google-${{ steps.get_latest_release.outputs.new_version }}-rc${{ github.run_number }} \
+        --title "Release modules/google-${{ steps.get_latest_release.outputs.new_version }}-rc${{ github.run_number }}" \
         --generate-notes \
         --draft=false \
         --latest=false \
@@ -67,7 +112,7 @@ jobs:
       uses: rtCamp/action-slack-notify@v2
       env:
         SLACK_COLOR: 'success'
-        SLACK_MESSAGE: 'Released modules/k8s/loki-${{ steps.get_latest_release.outputs.new_version }}-rc${{ github.run_number }} ${{ env.RELEASE_URL }}'
+        SLACK_MESSAGE: 'Released modules/google-${{ steps.get_latest_release.outputs.new_version }}-rc${{ github.run_number }} ${{ env.RELEASE_URL }}'
         SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
         SLACK_ICON_EMOJI: ${{ secrets.SLACK_ICON_EMOJI }}
@@ -78,7 +123,7 @@ jobs:
       uses: rtCamp/action-slack-notify@v2
       env:
         SLACK_COLOR: 'failure'
-        SLACK_MESSAGE: 'Failed to update modules/k8s/loki-${{ steps.get_latest_release.outputs.new_version }}-rc${{ github.run_number }} on main'
+        SLACK_MESSAGE: 'Failed to update modules/google-${{ steps.get_latest_release.outputs.new_version }}-rc${{ github.run_number }} on main'
         SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
         SLACK_ICON_EMOJI: ${{ secrets.SLACK_ICON_EMOJI }}
diff --git a/.github/workflows/k8s_pull.yml b/.github/workflows/k8s_pull.yml
--- a/.github/workflows/k8s_pull.yml
+++ b/.github/workflows/k8s_pull.yml
@@ -1,20 +1,26 @@
-name: PR modules/k8s/prometheus
+name: PR modules/k8s
 
 on:
   pull_request:
     branches:
       - main
     paths:
-      - 'modules/k8s/prometheus/**'
+      - 'modules/k8s/**'
   workflow_dispatch:
 
 jobs:
   build:
-    name: Test modules/k8s/prometheus
+    name: PR modules/k8s
     runs-on: ubuntu-latest
     steps:
-    - name: Checkout code
-      uses: actions/checkout@v3
+    - uses: actions/checkout@v4
+      with:
+        fetch-depth: 0
+
+    - name: Get changed files
+      id: changed-files
+      uses: tj-actions/changed-files@v42
+    
     - name: Run tests
       env:
         GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
@@ -26,6 +32,17 @@ jobs:
         AWS_REGION:  ${{ secrets.AWS_REGION }}
         PR_BRANCH: ${{ github.event.pull_request.head.ref }}
         ENTIGO_INFRALIB_DESTROY: true
-      run: |
-        modules/k8s/prometheus/test.sh
+      run: | 
+        echo "Changed modules:"
+        for module in $(for file in ${{ steps.changed-files.outputs.all_changed_files }}; do
+            echo "$file" | grep "modules/k8s" | cut -d'/' -f1-3
+        done | sort -u )
+        do
+          ${module}/test.sh
+          if [ $? -ne 0 ]
+          then
+            echo "Failed ${module}"
+            exit 2
+          fi
+        done
 
