Change concurrency for PR and main commits

diff --git a/.github/workflows/k8s_main.yml b/.github/workflows/k8s_main.yml
--- a/.github/workflows/k8s_main.yml
+++ b/.github/workflows/k8s_main.yml
@@ -12,15 +12,19 @@ jobs:
   build:
     name: Test modules/k8s
     runs-on: ubuntu-latest
-    concurrency:
-      group: pr-modules-test
-      cancel-in-progress: false
     steps:
     - name: Free disk space
       run: |
         # Remove large preinstalled tools
         sudo rm -rf /usr/share/dotnet /opt/ghc /opt/hostedtoolcache/CodeQL /usr/local/lib/android
         sudo docker image prune --all --force
+    - name: Wait for other workflow runs
+      uses: softprops/turnstyle@v2
+      with:
+        # Abort if waiting longer than 30 minutes
+        abort-after-seconds: 3600
+      env:
+        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
     - uses: actions/checkout@v4
       with:
         fetch-depth: 0
@@ -46,56 +50,25 @@ jobs:
         ENTIGO_INFRALIB_DESTROY: false
       run: |
         source common/generate_config.sh
-        prepare_agent
-        echo "sources:
-            - url: https://github.com/entigolabs/entigo-infralib
-              version: main
-              force_version: true
-        steps:" > agents/config.yaml
-
-        default_aws_conf
-        default_google_conf
-        full_k8s_conf
-        rm -rf agents/aws_ext agents/aws_min agents/aws_us
-
         docker pull $ENTIGO_INFRALIB_IMAGE
-        run_agents apps
         docker pull $KUBESCORE_IMAGE
-
         google_auth_login
-        
         gcloud container clusters get-credentials pri-infra-gke --region $GOOGLE_REGION
         gcloud container clusters get-credentials biz-infra-gke --region $GOOGLE_REGION
         aws eks update-kubeconfig --region $AWS_REGION --name pri-infra-eks
         aws eks update-kubeconfig --region $AWS_REGION --name biz-infra-eks
         
-        PIDS=""
         echo "Changed modules:"
         for module in $(for file in ${{ steps.changed-files.outputs.all_changed_files }} ${{ steps.changed-files.outputs.deleted_files }}; do
             echo "$file" | grep "modules/k8s" | cut -d'/' -f1-3
         done | sort -u )
         do
-          ${module}/test.sh testonly &
-          PIDS="$PIDS $!=${module}"
+          ${module}/test.sh
+          if [ $? -ne 0 ]
+            echo "${module} Failed"
+            exit 1
+          fi
         done
-
-        FAIL=""
-        for p in $PIDS; do
-            pid=$(echo $p | cut -d"=" -f1)
-            name=$(echo $p | cut -d"=" -f2)
-            wait $pid || FAIL="$FAIL $p"
-            if [[ $FAIL == *$p* ]]
-            then
-              echo "$p Failed"
-            else
-              echo "$p Done"
-            fi
-        done
-        if [ "$FAIL" != "" ]
-        then
-          echo "FAILED TESTS $FAIL"
-          exit 2
-        fi
 
     - name: Get latest release
       id: get_latest_release
