Add google secrets for hostnames for k8s modules

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -231,6 +231,21 @@ jobs:
           echo "FAILED JOBS $FAIL"
           exit 1
         fi
+        PIDS=""
+
+        modules/k8s/grafana/test.sh &
+        PIDS="$PIDS $!"
+        
+        FAIL=0
+        for p in $PIDS; do
+            wait $p || let "FAIL+=1"
+            echo $p $FAIL
+        done
+        if [ "$FAIL" -ne 0 ]
+        then
+          echo "FAILED JOBS $FAIL"
+          exit 1
+        fi
     - name: Slack Failed To Install Latest Release Message
       if: ${{ failure() }}
       uses: rtCamp/action-slack-notify@v2
