Rd-423 - Add google agent inputs and remove excessive permissions for google (#634)

diff --git a/.github/workflows/release.yaml b/.github/workflows/release.yaml
--- a/.github/workflows/release.yaml
+++ b/.github/workflows/release.yaml
@@ -210,8 +210,6 @@ jobs:
         PIDS="$PIDS $!"
         modules/k8s/loki/test.sh &
         PIDS="$PIDS $!"
-        modules/k8s/promtail/test.sh &
-        PIDS="$PIDS $!"
         modules/k8s/mimir/test.sh &
         PIDS="$PIDS $!"
         modules/k8s/grafana/test.sh &
@@ -221,6 +219,23 @@ jobs:
         modules/k8s/kiali/test.sh &
         PIDS="$PIDS $!"
         modules/k8s/entigo-portal-agent/test.sh &
+        PIDS="$PIDS $!"
+        
+        FAIL=0
+        for p in $PIDS; do
+            wait $p || let "FAIL+=1"
+            echo $p $FAIL
+        done
+        if [ "$FAIL" -ne 0 ]
+        then
+          echo "FAILED JOBS $FAIL"
+          exit 1
+        fi
+        PIDS=""
+
+        modules/k8s/promtail/test.sh &
+        PIDS="$PIDS $!"
+        modules/k8s/grafana/test.sh &
         PIDS="$PIDS $!"
         
         FAIL=0
