Separate stable install of aws, goole and k8s resources.

diff --git a/.github/workflows/stable.yaml b/.github/workflows/stable.yaml
--- a/.github/workflows/stable.yaml
+++ b/.github/workflows/stable.yaml
@@ -6,8 +6,74 @@ on:
   workflow_dispatch:
 
 jobs:
-  install_stable:
-    name: Install stable release
+  install_stable_aws:
+    name: Install stable AWS
+    runs-on: ubuntu-latest
+    steps:
+    - name: Get latest release
+      id: get_latest_release
+      uses: actions/github-script@v6
+      with:
+        script: |
+          const latestStableRelease = await github.rest.repos.getLatestRelease({ owner: context.repo.owner, repo: context.repo.repo });
+          if (latestStableRelease) {
+            core.setOutput('release_tag', latestStableRelease.data.tag_name);
+            core.info('Latest stable release tag: ' + latestStableRelease.data.tag_name);
+          } else {
+            core.setFailed('No stable releases found');
+          }
+
+    - name: Checkout code of latest release
+      uses: actions/checkout@v3
+      with:
+        ref: ${{ steps.get_latest_release.outputs.release_tag }}
+    - name: Create resources based on latest release
+      id: create_latest_release
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        AWS_REGION:  ${{ secrets.AWS_REGION }}
+        PR_BRANCH: "main"
+        ENTIGO_INFRALIB_DESTROY: false
+      run: |
+        echo "Current stable release commit is $(git rev-parse HEAD)"
+        PIDS=""
+        modules/aws/cost-alert/test.sh &
+        PIDS="$PIDS $!"
+        modules/aws/hello-world/test.sh &
+        PIDS="$PIDS $!"
+        modules/aws/vpc/test.sh 
+        modules/aws/route53/test.sh &
+        PIDS="$PIDS $!"
+        modules/aws/eks/test.sh
+        modules/aws/ec2/test.sh &
+        PIDS="$PIDS $!"
+        modules/aws/helm-git/test.sh &
+        PIDS="$PIDS $!"
+        modules/aws/crossplane/test.sh
+        FAIL=0
+        for p in $PIDS; do
+            wait $p || let "FAIL+=1"
+            echo $p $FAIL
+        done
+        if [ "$FAIL" -ne 0 ]
+        then
+          echo "FAILED JOBS $FAIL"
+          exit 1
+        fi
+    - name: Slack Failed To Install Latest Release Message
+      if: ${{ failure() }}
+      uses: rtCamp/action-slack-notify@v2
+      env:
+        SLACK_COLOR: 'failure'
+        SLACK_MESSAGE: 'Fresh installation of latest release failed after Nuke for AWS.'
+        SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
+        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
+        SLACK_ICON_EMOJI: ${{ secrets.SLACK_ICON_EMOJI }}
+        SLACK_FOOTER: ""
+
+  install_stable_google:
+    name: Install stable Google
     runs-on: ubuntu-latest
     steps:
     - name: Get latest release
@@ -42,24 +108,69 @@ jobs:
       run: |
         echo "Current stable release commit is $(git rev-parse HEAD)"
         PIDS=""
-        modules/aws/cost-alert/test.sh &
-        PIDS="$PIDS $!"
-        modules/aws/hello-world/test.sh &
-        PIDS="$PIDS $!"
         modules/google/services/test.sh &
         PIDS="$PIDS $!"
-        modules/google/vpc/test.sh &
-        PIDS="$PIDS $!"
-        modules/aws/vpc/test.sh 
-        modules/aws/route53/test.sh &
-        PIDS="$PIDS $!"
+        modules/google/vpc/test.sh
         modules/google/gke/test.sh
-        modules/aws/eks/test.sh
-        modules/google/dns/test.sh &
-        PIDS="$PIDS $!"
+        modules/google/dns/test.sh
+        FAIL=0
+        for p in $PIDS; do
+            wait $p || let "FAIL+=1"
+            echo $p $FAIL
+        done
+        if [ "$FAIL" -ne 0 ]
+        then
+          echo "FAILED JOBS $FAIL"
+          exit 1
+        fi
+    - name: Slack Failed To Install Latest Release Message
+      if: ${{ failure() }}
+      uses: rtCamp/action-slack-notify@v2
+      env:
+        SLACK_COLOR: 'failure'
+        SLACK_MESSAGE: 'Fresh installation of latest release failed after Nuke for Google.'
+        SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
+        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
+        SLACK_ICON_EMOJI: ${{ secrets.SLACK_ICON_EMOJI }}
+        SLACK_FOOTER: ""
+  install_stable_k8s:
+    needs: [install_stable_google,install_stable_aws]
+    name: Install stable K8s
+    runs-on: ubuntu-latest
+    steps:
+    - name: Get latest release
+      id: get_latest_release
+      uses: actions/github-script@v6
+      with:
+        script: |
+          const latestStableRelease = await github.rest.repos.getLatestRelease({ owner: context.repo.owner, repo: context.repo.repo });
+          if (latestStableRelease) {
+            core.setOutput('release_tag', latestStableRelease.data.tag_name);
+            core.info('Latest stable release tag: ' + latestStableRelease.data.tag_name);
+          } else {
+            core.setFailed('No stable releases found');
+          }
+
+    - name: Checkout code of latest release
+      uses: actions/checkout@v3
+      with:
+        ref: ${{ steps.get_latest_release.outputs.release_tag }}
+    - name: Create resources based on latest release
+      id: create_latest_release
+      env:
+        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
+        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
+        AWS_REGION:  ${{ secrets.AWS_REGION }}
+        GOOGLE_PROJECT: ${{ secrets.GOOGLE_PROJECT }}
+        GOOGLE_REGION: ${{ secrets.GOOGLE_REGION }}
+        GOOGLE_ZONE:  ${{ secrets.GOOGLE_ZONE }}
+        GOOGLE_CREDENTIALS:  ${{ secrets.GOOGLE_CREDENTIALS }}
+        PR_BRANCH: "main"
+        ENTIGO_INFRALIB_DESTROY: false
+      run: |
+        echo "Current stable release commit is $(git rev-parse HEAD)"
+        PIDS=""
         providers/test.sh &
-        PIDS="$PIDS $!"
-        modules/aws/ec2/test.sh &
         PIDS="$PIDS $!"
         modules/k8s/hello-world/test.sh &
         PIDS="$PIDS $!"
@@ -67,14 +178,10 @@ jobs:
         PIDS="$PIDS $!"
         modules/k8s/metrics-server/test.sh &
         PIDS="$PIDS $!"
-
-        modules/aws/helm-git/test.sh &
-        PIDS="$PIDS $!"
         modules/k8s/istio-base/test.sh &
         PIDS="$PIDS $!"
         modules/k8s/istio-istiod/test.sh &
         PIDS="$PIDS $!"
-        modules/aws/crossplane/test.sh
         modules/k8s/crossplane/test.sh
         modules/k8s/external-secrets/test.sh &
         PIDS="$PIDS $!"
@@ -111,7 +218,7 @@ jobs:
       uses: rtCamp/action-slack-notify@v2
       env:
         SLACK_COLOR: 'failure'
-        SLACK_MESSAGE: 'Fresh installation of latest release failed after Nuke.'
+        SLACK_MESSAGE: 'Fresh installation of latest release failed after Nuke for K8S.'
         SLACK_USERNAME: ${{ secrets.SLACK_USERNAME }}
         SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
         SLACK_ICON_EMOJI: ${{ secrets.SLACK_ICON_EMOJI }}
