Update release.yaml and stable.yaml for k8s/crossplane modules

diff --git a/.github/workflows/stable.yaml b/.github/workflows/stable.yaml
--- a/.github/workflows/stable.yaml
+++ b/.github/workflows/stable.yaml
@@ -206,7 +206,21 @@ jobs:
         PIDS="$PIDS $!"
         modules/k8s/istio-istiod/test.sh &
         PIDS="$PIDS $!"
-        modules/k8s/crossplane/test.sh &
+        modules/k8s/crossplane-core/test.sh &
+        PIDS="$PIDS $!"
+        FAIL=0
+        for p in $PIDS; do
+            wait $p || let "FAIL+=1"
+            echo $p $FAIL
+        done
+        if [ "$FAIL" -ne 0 ]
+        then
+          echo "FAILED JOBS $FAIL"
+          exit 1
+        fi
+        PIDS=""
+
+        modules/k8s/crossplane-aws/test.sh &
         PIDS="$PIDS $!"
         modules/k8s/crossplane-google/test.sh &
         PIDS="$PIDS $!"
@@ -234,6 +248,8 @@ jobs:
         modules/k8s/mimir/test.sh &
         PIDS="$PIDS $!"
         modules/k8s/grafana/test.sh &
+        PIDS="$PIDS $!"
+        modules/k8s/crossplane-k8s/test.sh &
         PIDS="$PIDS $!"
         
         FAIL=0
